/*
Solved date
- 230921
*/
SELECT
    MCDP_CD AS '진료과코드'
    , COUNT(*) AS '5월예약건수'
FROM APPOINTMENT
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m') = '2022-05'
GROUP BY MCDP_CD
ORDER BY 2, 1;


# -- 2022년 5월에 예약한 환자 수를 진료과코드 별로 조회
# SELECT MCDP_CD AS '진료과코드', COUNT(*) AS '5월예약건수'
# FROM APPOINTMENT
# WHERE YEAR(APNT_YMD)=2022 AND MONTH(APNT_YMD) = 5
# -- WHERE APNT_YMD LIKE '2022-05%'
# GROUP BY MCDP_CD
# ORDER BY 2, 1;